### ISSUE TITLE
black background when thumbnailing PNG's

### ISSUE THREAD

**Issue by Manolico** [knarka/fikaba#1]
When i upload a PNG image without background (Transparent) the thumbnail shows  a black background.
Does the problem the script hasn't Oekaki?

**Comment by mxrnx** [comment]
The thumbnails are JPGs, and thus do not support transparency. Most engines (vichan and yotsuba at the very least) deal with this by making the background of the JPG a color that matches with the default colorscheme, so I think I'll add a setting for that where the end user can choose the color.

Also, what do you mean by "Does the problem the script hasn't Oekaki?". This problem isn't being caused by fikaba's lack of oekaki, if that's what you're asking.

**Comment by mxrnx** [comment]
If you update your installation you should be able to configure the background color now. It works on my end
